winget install --accept-package-agreements --accept-source-agreements Microsoft.PowerShell
winget install --accept-package-agreements --accept-source-agreements Notepad++.Notepad++
winget install --accept-package-agreements --accept-source-agreements Google.Chrome
winget install --accept-package-agreements --accept-source-agreements AnyDesk.AnyDesk
winget install --accept-package-agreements --accept-source-agreements RARLab.WinRAR
winget uninstall --disable-interactivity "Microsoft.Edge"
winget uninstall --disable-interactivity "ARP\Machine\X86\Microsoft Edge Update"
winget uninstall --disable-interactivity "Microsoft.EdgeWebView2Runtime"
winget uninstall --disable-interactivity "Microsoft.OneDrive"
winget uninstall --disable-interactivity "MSIX\AppUp.IntelGraphicsExperience_1.100.5688.0_x64__8j3eq9eme6ctt"
winget uninstall --disable-interactivity "MSIX\Clipchamp.Clipchamp_4.5.10220.0_x64__yxz26nhyzhsrt"
winget uninstall --disable-interactivity "Microsoft.Teams"
winget uninstall --disable-interactivity "MSIX\Microsoft.AV1VideoExtension_2.0.7.0_x64__8wekyb3d8bbwe"
winget uninstall --disable-interactivity "MSIX\Microsoft.AVCEncoderVideoExtension_1.1.23.0_x64__8wekyb3d8bbwe"
winget uninstall --disable-interactivity "MSIX\Microsoft.ApplicationCompatibilityEnhancements_1.2511.9.0_x64__8wekyb3d8bbwe"
winget uninstall --disable-interactivity "MSIX\Microsoft.BingNews_4.55.62231.0_x64__8wekyb3d8bbwe"
winget uninstall --disable-interactivity "MSIX\Microsoft.BingSearch_1.1.43.0_x64__8wekyb3d8bbwe"
winget uninstall --disable-interactivity "MSIX\Microsoft.BingWeather_4.54.63029.0_x64__8wekyb3d8bbwe"
winget uninstall --disable-interactivity "Microsoft.AppInstaller"
winget uninstall --disable-interactivity "MSIX\Microsoft.GamingApp_2602.1001.5.0_x64__8wekyb3d8bbwe"
winget uninstall --disable-interactivity "MSIX\Microsoft.GetHelp_10.2409.33293.0_x64__8wekyb3d8bbwe"
winget uninstall --disable-interactivity "MSIX\Microsoft.HEIFImageExtension_1.2.29.0_x64__8wekyb3d8bbwe"
winget uninstall --disable-interactivity "MSIX\Microsoft.Ink.Handwriting.Main.pt-BR.1.0_0.1082.2350.0_x64__8wekyb3d8bbwe"
winget uninstall --disable-interactivity "MSIX\Microsoft.Ink.Handwriting.pt-BR.1.0_0.1082.2350.0_x64__8wekyb3d8bbwe"
winget uninstall --disable-interactivity "MSIX\Microsoft.Ink.Handwriting.pt-BR.1.0_0.1082.2350.0_x86__8wekyb3d8bbwe"
winget uninstall --disable-interactivity "MSIX\Microsoft.MPEG2VideoExtension_1.2.13.0_x64__8wekyb3d8bbwe"
winget uninstall --disable-interactivity "MSIX\Microsoft.MicrosoftEdge.Stable_145.0.3800.70_neutral__8wekyb3d8bbwe"
winget uninstall --disable-interactivity "Microsoft.Edge"  
winget uninstall --disable-interactivity "ARP\Machine\X86\Microsoft Edge Update"
winget uninstall --disable-interactivity "Microsoft.EdgeWebView2Runtime"  
winget uninstall --disable-interactivity "ARP\Machine\X86\{F132AF7F-7BCA-4EDE-8A7C-958108FE7DBC}" 
winget uninstall --disable-interactivity "Microsoft.OneDrive" 
winget uninstall --disable-interactivity "MSIX\AppUp.IntelGraphicsExperience_1.100.5688.0_x64__8j3eq9eme6ctt" 
winget uninstall --disable-interactivity "MSIX\Clipchamp.Clipchamp_4.5.10220.0_x64__yxz26nhyzhsrt"
winget uninstall --disable-interactivity "Microsoft.Teams" 
winget uninstall --disable-interactivity "MSIX\Microsoft.AV1VideoExtension_2.0.7.0_x64__8wekyb3d8bbwe"  
winget uninstall --disable-interactivity "MSIX\Microsoft.AVCEncoderVideoExtension_1.1.23.0_x64__8wekyb3d8bbwe"
winget uninstall --disable-interactivity "MSIX\Microsoft.ApplicationCompatibilityEnhancements_1.2511.9.0_x64__8wekyb3d8bbwe 
winget uninstall --disable-interactivity "MSIX\Microsoft.BingNews_4.55.62231.0_x64__8wekyb3d8bbwe"
winget uninstall --disable-interactivity "MSIX\Microsoft.BingSearch_1.1.43.0_x64__8wekyb3d8bbwe"  
winget uninstall --disable-interactivity "MSIX\Microsoft.BingWeather_4.54.63029.0_x64__8wekyb3d8bbwe"
winget uninstall --disable-interactivity "Microsoft.AppInstaller"
winget uninstall --disable-interactivity "MSIX\Microsoft.GamingApp_2602.1001.5.0_x64__8wekyb3d8bbwe" 
winget uninstall --disable-interactivity "MSIX\Microsoft.GetHelp_10.2409.33293.0_x64__8wekyb3d8bbwe" 
winget uninstall --disable-interactivity "MSIX\Microsoft.HEIFImageExtension_1.2.29.0_x64__8wekyb3d8bbwe"
winget uninstall --disable-interactivity "MSIX\Microsoft.Ink.Handwriting.Main.pt-BR.1.0_0.1082.2350.0_x64__8wekyb3d8bbwe" 
winget uninstall --disable-interactivity "MSIX\Microsoft.Ink.Handwriting.pt-BR.1.0_0.1082.2350.0_x64__8wekyb3d8bbwe"
winget uninstall --disable-interactivity "MSIX\Microsoft.Ink.Handwriting.pt-BR.1.0_0.1082.2350.0_x86__8wekyb3d8bbwe"
winget uninstall --disable-interactivity "MSIX\Microsoft.MPEG2VideoExtension_1.2.13.0_x64__8wekyb3d8bbwe"  
winget uninstall --disable-interactivity "MSIX\Microsoft.MicrosoftEdge.Stable_145.0.3800.70_neutral__8wekyb3d8bbwe" 
winget uninstall --disable-interactivity "MSIX\Microsoft.MicrosoftOfficeHub_19.2602.54021.0_x64__8wekyb3d8bbwe"  
winget uninstall --disable-interactivity "MSIX\Microsoft.MicrosoftSolitaireCollection_4.25.1130.0_x64__8wekyb3d8bbwe"  
winget uninstall --disable-interactivity "MSIX\Microsoft.MicrosoftStickyNotes_6.1.4.0_x64__8wekyb3d8bbwe"  
winget uninstall --disable-interactivity "MSIX\Microsoft.MixedReality.Portal_2000.21051.1282.0_x64__8wekyb3d8bbwe"  
winget uninstall --disable-interactivity "MSIX\Microsoft.NET.Native.Framework.2.2_2.2.29512.0_x64__8wekyb3d8bbwe"
winget uninstall --disable-interactivity "MSIX\Microsoft.NET.Native.Framework.2.2_2.2.29512.0_x86__8wekyb3d8bbwe"
winget uninstall --disable-interactivity "MSIX\Microsoft.NET.Native.Runtime.2.2_2.2.28604.0_x64__8wekyb3d8bbwe"  
winget uninstall --disable-interactivity "MSIX\Microsoft.NET.Native.Runtime.2.2_2.2.28604.0_x86__8wekyb3d8bbwe"  
winget uninstall --disable-interactivity "MSIX\Microsoft.Office.OneNote_16001.14326.22594.0_x64__8wekyb3d8bbwe"  
winget uninstall --disable-interactivity "MSIX\Microsoft.OutlookForWindows_1.2026.210.300_x64__8wekyb3d8bbwe" 
winget uninstall --disable-interactivity "MSIX\Microsoft.Paint_11.2512.221.0_x64__8wekyb3d8bbwe"  
winget uninstall --disable-interactivity "MSIX\Microsoft.People_10.2202.100.0_x64__8wekyb3d8bbwe" 
winget uninstall --disable-interactivity "MSIX\Microsoft.PowerAutomateDesktop_11.2602.145.0_x64__8wekyb3d8bbwe"  
winget uninstall --disable-interactivity "MSIX\Microsoft.RawImageExtension_2.5.7.0_x64__8wekyb3d8bbwe"  
winget uninstall --disable-interactivity "MSIX\Microsoft.ScreenSketch_11.2511.47.0_x64__8wekyb3d8bbwe"  
winget uninstall --disable-interactivity "MSIX\Microsoft.SecHealthUI_1000.29510.1001.0_x64__8wekyb3d8bbwe" 
winget uninstall --disable-interactivity "MSIX\Microsoft.SkypeApp_15.150.3125.0_x64__kzf8qxf38zg5c"  
winget uninstall --disable-interactivity "MSIX\Microsoft.StartExperiencesApp_1.229.1.0_x64__8wekyb3d8bbwe" 
winget uninstall --disable-interactivity "MSIX\Microsoft.StorePurchaseApp_22512.1401.1.0_x64__8wekyb3d8bbwe"  
winget uninstall --disable-interactivity "MSIX\Microsoft.Todos_2.168.6211.0_x64__8wekyb3d8bbwe"
winget uninstall --disable-interactivity "Microsoft.UI.Xaml.2.7" 
winget uninstall --disable-interactivity "Microsoft.UI.Xaml.2.7" 
winget uninstall --disable-interactivity "Microsoft.UI.Xaml.2.8" 
winget uninstall --disable-interactivity "Microsoft.UI.Xaml.2.8" 
winget uninstall --disable-interactivity "Microsoft.VCLibs.Desktop.14" 
winget uninstall --disable-interactivity "Microsoft.VCLibs.Desktop.14" 
winget uninstall --disable-interactivity "MSIX\Microsoft.VCLibs.140.00_14.0.33519.0_x64__8wekyb3d8bbwe" 
winget uninstall --disable-interactivity "MSIX\Microsoft.VCLibs.140.00_14.0.33519.0_x86__8wekyb3d8bbwe" 
winget uninstall --disable-interactivity "MSIX\Microsoft.VP9VideoExtensions_1.2.12.0_x64__8wekyb3d8bbwe"
winget uninstall --disable-interactivity "MSIX\Microsoft.WebMediaExtensions_1.2.17.0_x64__8wekyb3d8bbwe"
winget uninstall --disable-interactivity "MSIX\Microsoft.WebpImageExtension_1.2.14.0_x64__8wekyb3d8bbwe"
winget uninstall --disable-interactivity "MSIX\Microsoft.WidgetsPlatformRuntime_1.6.14.0_x64__8wekyb3d8bbwe"  
winget uninstall --disable-interactivity "MSIX\Microsoft.Windows.DevHome_0.0.0.0_x64__8wekyb3d8bbwe" 
winget uninstall --disable-interactivity "MSIX\Microsoft.Windows.Photos_2025.11120.5001.0_x64__8wekyb3d8bbwe" 
winget uninstall --disable-interactivity "MSIX\Microsoft.WindowsAlarms_11.2512.0.0_x64__8wekyb3d8bbwe"  
winget uninstall --disable-interactivity "MSIX\Microsoft.WindowsAppRuntime.1.5_5001.373.1736.0_x64__8wekyb3d8bbwe"  
winget uninstall --disable-interactivity "MSIX\Microsoft.WindowsAppRuntime.1.5_5001.373.1736.0_x86__8wekyb3d8bbwe"  
winget uninstall --disable-interactivity "MSIX\Microsoft.WindowsAppRuntime.1.6_6000.519.329.0_x64__8wekyb3d8bbwe"
winget uninstall --disable-interactivity "MSIX\Microsoft.WindowsAppRuntime.1.6_6000.519.329.0_x86__8wekyb3d8bbwe"
winget uninstall --disable-interactivity "MSIX\Microsoft.WindowsAppRuntime.1.7_7000.770.750.0_x64__8wekyb3d8bbwe"
winget uninstall --disable-interactivity "MSIX\Microsoft.WindowsAppRuntime.1.7_7000.770.750.0_x86__8wekyb3d8bbwe"
winget uninstall --disable-interactivity "MSIX\Microsoft.WindowsAppRuntime.1.8_8000.770.947.0_x64__8wekyb3d8bbwe"
winget uninstall --disable-interactivity "MSIX\Microsoft.WindowsAppRuntime.1.8_8000.770.947.0_x86__8wekyb3d8bbwe"
winget uninstall --disable-interactivity "MSIX\Microsoft.WindowsCalculator_11.2508.4.0_x64__8wekyb3d8bbwe" 

winget uninstall --disable-interactivity "MSIX\Microsoft.WindowsFeedbackHub_1.2602.13304.0_x64__8wekyb3d8bbwe"
winget uninstall --disable-interactivity "MSIX\Microsoft.WindowsMaps_11.2506.3.0_x64__8wekyb3d8bbwe" 
winget uninstall --disable-interactivity "MSIX\Microsoft.WindowsNotepad_11.2510.14.0_x64__8wekyb3d8bbwe"
winget uninstall --disable-interactivity "MSIX\Microsoft.WindowsSoundRecorder_11.2512.0.0_x64__8wekyb3d8bbwe" 

winget uninstall --disable-interactivity "Microsoft.WindowsTerminal"
winget uninstall --disable-interactivity "MSIX\Microsoft.Winget.Source_2026.226.1147.24_neutral__8wekyb3d8bbwe"  
winget uninstall --disable-interactivity "MSIX\Microsoft.Xbox.TCUI_1.24.10001.0_x64__8wekyb3d8bbwe"  
winget uninstall --disable-interactivity "MSIX\Microsoft.XboxGameOverlay_1.54.4001.0_x64__8wekyb3d8bbwe"
winget uninstall --disable-interactivity "MSIX\Microsoft.XboxGamingOverlay_7.326.2102.0_x64__8wekyb3d8bbwe"
winget uninstall --disable-interactivity "MSIX\Microsoft.XboxIdentityProvider_12.130.16001.0_x64__8wekyb3d8bbwe" 
winget uninstall --disable-interactivity "MSIX\Microsoft.XboxSpeechToTextOverlay_1.21.13002.0_x64__8wekyb3d8bbwe"
winget uninstall --disable-interactivity "MSIX\Microsoft.YourPhone_1.26011.42.0_x64__8wekyb3d8bbwe"  
winget uninstall --disable-interactivity "MSIX\Microsoft.ZuneMusic_11.2512.10.0_x64__8wekyb3d8bbwe"  
winget uninstall --disable-interactivity "MSIX\Microsoft.ZuneVideo_10.25121.10051.0_x64__8wekyb3d8bbwe" 
winget uninstall --disable-interactivity "MSIX\MicrosoftCorporationII.QuickAssist_2.0.29.0_x64__8wekyb3d8bbwe"
winget uninstall --disable-interactivity "MSIX\MicrosoftWindows.Client.WebExperience_526.1202.40.0_x64__cw5n1h2txyewy" 
winget uninstall --disable-interactivity "MSIX\MicrosoftWindows.CrossDevice_1.26011.30.0_x64__cw5n1h2txyewy"  
winget uninstall --disable-interactivity "MSIX\microsoft.windowscommunicationsapps_16005.14326.22342.0_x64__8wekyb3d8bbwe"
winget uninstall --disable-interactivity "9NBLGGH4VF97"
winget uninstall --disable-interactivity "Email e Calendário"
winget uninstall --disable-interactivity "Hub de Comentários"
winget uninstall --disable-interactivity "Microsoft.549981C3F5F10_8wekyb3d8bbwe"
winget uninstall --disable-interactivity "Microsoft.BingNews_8wekyb3d8bbwe"
winget uninstall --disable-interactivity "Microsoft.BingWeather_8wekyb3d8bbwe"
winget uninstall --disable-interactivity "Microsoft.GamingApp_8wekyb3d8bbwe"
winget uninstall --disable-interactivity "Microsoft.MicrosoftOfficeHub_8wekyb3d8bbwe"
winget uninstall --disable-interactivity "Microsoft.MicrosoftSolitaireCollection_8wekyb3"
winget uninstall --disable-interactivity "Microsoft.MicrosoftStickyNotes_8wekyb3"
winget uninstall --disable-interactivity "Microsoft.OutlookForWindows_8wekyb3d8bbwe"
winget uninstall --disable-interactivity "Microsoft.People_8wekyb3d8bbwe"
winget uninstall --disable-interactivity "Microsoft.Todos_8wekyb3d8bbwe"
winget uninstall --disable-interactivity "Microsoft.WindowsAlarms_8wekyb3d8bbwe"
winget uninstall --disable-interactivity "Microsoft.WindowsFeedbackHub_"
winget uninstall --disable-interactivity "Microsoft.WindowsMaps_8wekyb3d8bbwe"
winget uninstall --disable-interactivity "Microsoft.ZuneMusic_8wekyb3d8bbwe"
winget uninstall --disable-interactivity "Microsoft.ZuneVideo_8wekyb3d8bbwe"
winget uninstall --disable-interactivity "MicrosoftCorporationII.MicrosoftFamily_8wekyb3d8bbwe"
winget uninstall --disable-interactivity "MicrosoftTeams_8wekyb3d8bbwe"
winget uninstall --disable-interactivity "Notas Autoadesivas da Microsoft"
winget uninstall --disable-interactivity "Solitaire & Casual Games"
winget uninstall --disable-interactivity "microsoft.windowscommunicationsapps_8wekyb3d"
winget uninstall --disable-interactivity C6FD611E-7EFE-488C-A0E0-974C09EF6473
winget uninstall --disable-interactivity Clipchamp.Clipchamp_yxz26nhyzhsrt
winget uninstall --disable-interactivity Microsoft.549981C3F5F10_8wekyb3d8bbwe
winget uninstall --disable-interactivity Microsoft.BingNews_8wekyb3d8bbwe
winget uninstall --disable-interactivity Microsoft.BingWeather_8wekyb3d8bbwe
winget uninstall --disable-interactivity Microsoft.GamingApp_8wekyb3d8bbwe
winget uninstall --disable-interactivity Microsoft.GetHelp_8wekyb3d8bbwe
winget uninstall --disable-interactivity Microsoft.MicrosoftOfficeHub_8wekyb3d8bbwe
winget uninstall --disable-interactivity Microsoft.MicrosoftSolitaireCollection_8wekyb3d8bbwe
winget uninstall --disable-interactivity Microsoft.MicrosoftStickyNotes_8wekyb3d8bbwe
winget uninstall --disable-interactivity Microsoft.OutlookForWindows_8wekyb3d8bbwe
winget uninstall --disable-interactivity Microsoft.People_8wekyb3d8bbwe
winget uninstall --disable-interactivity Microsoft.PowerAutomateDesktop_8wekyb3d8bbwe
winget uninstall --disable-interactivity Microsoft.Todos_8wekyb3d8bbwe
winget uninstall --disable-interactivity Microsoft.WindowsAlarms_8wekyb3d8bbwe
winget uninstall --disable-interactivity Microsoft.WindowsFeedbackHub_8wekyb3d8bbwe
winget uninstall --disable-interactivity Microsoft.WindowsMaps_8wekyb3d8bbwe
winget uninstall --disable-interactivity Microsoft.WindowsNotepad_8wekyb3d8bbwe
winget uninstall --disable-interactivity Microsoft.Xbox.TCUI_8wekyb3d8bbwe
winget uninstall --disable-interactivity Microsoft.XboxGameOverlay_8wekyb3d8bbwe
winget uninstall --disable-interactivity Microsoft.XboxGamingOverlay_8wekyb3d8bbwe
winget uninstall --disable-interactivity Microsoft.XboxIdentityProvider_8wekyb3d8bbwe
winget uninstall --disable-interactivity Microsoft.XboxSpeechToTextOverlay_8wekyb3d8bbwe
winget uninstall --disable-interactivity Microsoft.YourPhone_8wekyb3d8bbwe
winget uninstall --disable-interactivity Microsoft.ZuneMusic_8wekyb3d8bbwe
winget uninstall --disable-interactivity Microsoft.ZuneVideo_8wekyb3d8bbwe
winget uninstall --disable-interactivity MicrosoftCorporationII.MicrosoftFamily_8wekyb3d8bbwe
winget uninstall --disable-interactivity MicrosoftCorporationII.QuickAssist_8wekyb3d8bbwe
winget uninstall --disable-interactivity MicrosoftTeams_8wekyb3d8bbwe
winget uninstall --disable-interactivity microsoft.windowscommunicationsapps_8wekyb3d8bbwe
